module.exports = Object.freeze({
   ENDGRID_API_KEY: "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",
   API_KEY_MAILJET: "173991db969acca92f875011b01c1ed1",
   API_SECRET_MAILJET: "28d64db58e18130adcbf7a71970884c6",
   CAB_IN_PROGRESS_DRIVER_SCREEN: "CabInProgressDriverScreen",
   CLIENTE_SCREEN: "ClienteScreen",
   DRIVER_SCREEN: "DriverScreen",
   CAB_IN_PROGRESS_CLIENT_SCREEN: "CabInProgressClientScreen",
   LOG_IN_SCREEN: "LogInScreen",
   PENDING_YUBER_SCREEN: "PendingYuberScreen",
   SIGN_UP_SCREEN: "SignUpScreen",
   WAITING_DRIVER_SCREEN: "WaitingDriverScreen",
   WELCOME_SCREEN: "WelcomeScreen",
   RATE_USER_SCREEN: "RateUserScreen",
   MY_RIDES_DRIVER_SCREEN: "MyRidesScreen",
   CHAT_SCREEN: "ChatScreen",
   OTP_SCREEN: "OTPScreen",
   PHONE_SCREEN: "PhoneScreen",
   DRIVER_HOME_SCREEN: "DriverHomeScreen",
   estadoViaje: { TIEMPO_FINALIZADO: 1, RECHAZADO_POR_USUARIO: 2, TRANSCURSO: 3, FINALIZADO: 4 },
});
